### ISSUE TITLE
A question about the design of Chaos-loris

### ISSUE THREAD

**Issue by allomov** [strepsirrhini-army/chaos-loris#8]
Hey, @nebhale. 

Currently you need to run additional extra steps to sync up apps that you have in your CF. Is it a way to avoid this? Do you use some tool to populate app data automatically? Could you please tell why do you have such design?

Thank you very much,
Alex L.

**Comment by nebhale** [comment]
The `chaos-loris` application itself is intended to be small and focused on killing instances of application that it knows about.  We viewed the idea that it might discover all of the applications within a CF installation as a bit too broad, as it might result in applications that didn't expect to be killed being killed.  The application was designed to be paired with a Service Broker that would manage the collection of applications that `chaos-loris` knew about.  In this way, applications could bind to the service and that would indicate that they were ready to accept chaos against them.  Due to lack of demand, this part of the system was never implemented.

**Comment by allomov** [comment]
Thank you for the answer very much. That's a good idea to bring service broker here.

Is chaos-loris service broker opensourced? Can we use it?

**Comment by allomov** [comment]
Since I was not to find any such service broker online, I will need to write the service broker by myself. I guess this may solve my problem.
